[info]
name		=	"Clafrica"
description = 	"Clafrica code for typingb african languages"
authors		=	["Resulam <contact@resulam.com>"]
website		=	"https://resulam.com"

[data]
single = { path = "./clafrica_single.toml" }
double = { path = "./clafrica_double.toml" }
